/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SoftA2Movie;

import java.util.*;
import java.io.*;
import java.time.LocalDateTime; 
// test comment


public class App {
    
    public Database db;
    public ArrayList<Cinema> cinemas;
    public static App myApp = new App(); 
    
    private App(){
        createObjects();
        // private to prevent anyone else from instantiating
    }
    public static App getAppInstance() {
        return myApp;
    }

    public String getGreeting() {
        return "Hello World!";
    }
    public String Greeting() {
        return " ####################  Naar Movie Booking System Is Now Running! #######################################";
    }
    
    public void GUIRunner() {
        GUIDefault.main(null);
    }
    public void createObjects(){
        
        // create database
        db = new Database();
        // set all csv 
        db.setBookingCsv("src/main/java/SoftA2Movie/resources/output/BookingSummary.csv");
        db.setGiftCardCsv("src/main/java/SoftA2Movie/resources/input/GiftCards.csv");
        db.setStaffCsv("src/main/java/SoftA2Movie/resources/input/Staff.csv");
        db.setCustomerCsv("src/main/java/SoftA2Movie/resources/input/CustomerLogins.csv");
        db.setMovieCsv("src/main/java/SoftA2Movie/resources/input/MovieDetails.csv");
        db.setShowCsv("src/main/java/SoftA2Movie/resources/input/ShowDetails.csv");
        db.setCancelledCsv("src/main/java/SoftA2Movie/resources/output/CancelledTransactions.csv");
        db.setCreditCardCsv("src/main/java/SoftA2Movie/resources/input/CreditCards.json");
        db.setUpcomingShowsCsv("src/main/java/SoftA2Movie/resources/output/UpcomingShows.csv");

        // parse all csv
        db.parseCreditCard();
        db.parseGiftCards();
        db.parseCustomers();
        db.parseMovies();
        db.parseShows();
        db.parseStaff();

        // cinema list 
        cinemas = new ArrayList<Cinema>(); 

        // create cinema objects
        Cinema ParraCinema = new Cinema("Paramatta", "159-175 Church St, Parramatta NSW 2150");
        Cinema ChatswoodCinema = new Cinema("Chatswood", " Anderson St, Chatswood NSW 2067");
        Cinema UsydCinema = new Cinema("Usyd", "Camperdown NSW 2006");
        Cinema CanterburyCinema = new Cinema("Canterbury", "100 Burwood Rd, Canterbury NSW 2134");  

        // add to cinema list list

        cinemas.add(ParraCinema);
        cinemas.add(ChatswoodCinema);
        cinemas.add(UsydCinema);
        cinemas.add(CanterburyCinema);
    }


    public static void main(String[] args) {

        new App().GUIRunner();
        System.out.println(new App().Greeting());
    }
        // left to do 
        // move booking metho into database 
        // add prcies to giftcards and creditcards
        // use the gitfcards when booking
        // change the csv paths when testing
        // credit card add.remove methods if jenny asks for it 
}
