/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SoftA2Movie;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.concurrent.*;
import static java.util.concurrent.TimeUnit.SECONDS;
import java.util.*;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CustomerBookingGUI extends javax.swing.JFrame {
    
    
    /**
     * Creates new form CustomerBookingGUI
     */
    public Customer customer;
    public final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    public CustomerBookingGUI(Customer customer) {
        this.customer = customer;
        Timer(this.customer);
        initComponents();
        
//        AUTOMATICALLY SET USER CREDIT DETAILS
        if (this.customer.detailsSaved){
        this.cardName.setText(this.customer.name);
        this.creditCardNo.setText(this.customer.creditCardNo);}
        
    }
// NEED TO FIX THIS !!!!!!!!!!!
    public void goBack() {
        new CustomerMainGUI(this.customer).setVisible(true);
        this.setVisible(false);

    }
    public void Timer(Customer customer){
        
        
        final Runnable runner = new Runnable() {
        int countdown = 120;
        
            public void run() {

                System.out.println("(Total Time Alloted 2min) -- TIME LEFT " + Integer.toString(countdown) + " (secs)");
                
                countdown--;

                if (countdown < 0) {
                    System.out.println("Booking took too long!");
                    scheduler.shutdown();
                    App.getAppInstance().db.updateCancelledBookingsCSV(0, customer.name, customer.username, LocalDateTime.now(), "Ran Out of Time");
                    goBack();
                }
            }

        };
        
        scheduler.scheduleAtFixedRate(runner, 0, 1, SECONDS);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        movieName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        bookMovie = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cinemaType = new javax.swing.JComboBox<>();
        cardName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allMovies = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationf = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        showingWeekf = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        timef = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        movieWantedf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        screenTypef = new javax.swing.JComboBox<>();
        applyFilter = new javax.swing.JButton();
        back = new javax.swing.JButton();
        saveCard = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        adultNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        childNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        studentNo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pensionerNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        frontNo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        backNo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        middleNo = new javax.swing.JTextField();
        giftCardNo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        creditCardNo = new javax.swing.JPasswordField();
        time = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Naar Cinemas ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(735, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        movieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Movie Title:");

        jLabel11.setText("Date Format (dd/mm/yyyy)");

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jLabel12.setText("Location");

        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        bookMovie.setText("Book Movie");
        bookMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookMovieActionPerformed(evt);
            }
        });

        jLabel13.setText("Show Time");

        jLabel15.setText("Cinema Type");

        cinemaType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronze", "Silver", "Gold" }));

        jLabel3.setText("Credit Card Name");

        jLabel4.setText("Credit Card Number");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        allMovies.setModel(App.getAppInstance().db.getJtableSForDisplay(App.getAppInstance().db.getShows()).getModel()

        );
        allMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allMoviesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allMovies);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel5.setText("Movies List");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Search Filters");

        locationf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Paramatta", "Mount Druitt", "Cantebury", "Usyd", "Chatswood" }));

        jLabel7.setText("Location");

        showingWeekf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movies This Week", "Upcoming Movies Next Week" }));
        showingWeekf.setToolTipText("");
        showingWeekf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showingWeekfActionPerformed(evt);
            }
        });

        jLabel8.setText("Showing");

        timef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Morning", "Afternoon", "Night" }));

        jLabel9.setText("Show Time");

        movieWantedf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieWantedfActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(movieWantedf);

        jLabel10.setText("Cinema Screen");

        jLabel17.setText("Movies of Interest (Comma Seperated)");

        screenTypef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Bronze", "Silver", "Gold" }));

        applyFilter.setText("Apply Filters");
        applyFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilterActionPerformed(evt);
            }
        });

        back.setText("Cancel & Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        saveCard.setText("Save Card Details");

        jLabel18.setText("Adult");

        adultNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultNoActionPerformed(evt);
            }
        });

        jLabel19.setText("Child");

        childNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childNoActionPerformed(evt);
            }
        });

        jLabel20.setText("Student");

        studentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNoActionPerformed(evt);
            }
        });

        jLabel21.setText("Pensioner");

        pensionerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensionerNoActionPerformed(evt);
            }
        });

        jLabel14.setText("No of Tickets:");

        jLabel22.setText("Front");

        frontNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontNoActionPerformed(evt);
            }
        });

        jLabel23.setText("Back");

        backNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backNoActionPerformed(evt);
            }
        });

        jLabel25.setText("Seat Choice:");

        jLabel26.setText("Middle");

        middleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNoActionPerformed(evt);
            }
        });

        jLabel27.setText("Gift Card Number");

        creditCardNo.setText("jPasswordField1");

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        jLabel16.setText("Note: Child and Pensioner get 80% discount on original price");

        jLabel24.setText("Students get 85% discount on original price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cardName, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(198, 198, 198)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel27)
                                                .addComponent(giftCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(creditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(185, 185, 185)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cinemaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(saveCard)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(7, 7, 7)
                                                .addComponent(adultNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel21))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addGap(7, 7, 7)
                                                        .addComponent(childNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel20)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pensionerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(studentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addGap(15, 15, 15)
                                                .addComponent(frontNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(backNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(middleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(bookMovie)
                                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(showingWeekf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(locationf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(timef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(screenTypef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(applyFilter))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 995, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 121, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cinemaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(childNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20)
                                            .addComponent(studentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(adultNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21)
                                            .addComponent(pensionerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel26)
                                            .addComponent(middleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(frontNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23)
                                            .addComponent(backNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giftCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(creditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(saveCard)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bookMovie)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(locationf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(timef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showingWeekf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(screenTypef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(applyFilter)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void movieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieNameActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void showingWeekfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showingWeekfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showingWeekfActionPerformed

    private void movieWantedfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieWantedfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieWantedfActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        scheduler.shutdown();
        
        App.getAppInstance().db.updateCancelledBookingsCSV(0, this.customer.name, this.customer.username, LocalDateTime.now(), "Left Site");
        new CustomerMainGUI(this.customer).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed

    private void applyFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterActionPerformed
        String loc = (String)locationf.getSelectedItem();
        String session = (String)timef.getSelectedItem();
        String showing = (String)showingWeekf.getSelectedItem();
        String type = (String)screenTypef.getSelectedItem();
        String moviesWanted = movieWantedf.getText();
        ArrayList<Showing> s = App.getAppInstance().db.getShows();
//        System.out.println(s.size());
        // i1 = We cant get all rows to display => Length
        // More than 6 rows and program fails
        
        if (loc.equals("All") && session.equals("All") && showing.equals("Movies This Week") &&  type.equals("All") && moviesWanted.equals("")){
            System.out.println("No Filters Applied!");
            s = App.getAppInstance().db.showingsTillNextMonday(s);
            allMovies.setModel(App.getAppInstance().db.getJtableSForDisplay(s).getModel());
        }
        else {
                System.out.println("Filters Applied");
                
                if (!loc.equals("All")){
                    s = App.getAppInstance().db.showingsByLocation(s, loc);
                }
                if (!session.equals("All")){
                    s = App.getAppInstance().db.showingsBySession(s, session);
                }
                if (showing.equals("Movies Today")){
                    s = App.getAppInstance().db.showingsByToday(s);
                }
                if (!type.equals("All")){
                    s = App.getAppInstance().db.showingsByScreenSize(s, type);
                }
                if (!moviesWanted.equals("")){
                    s = App.getAppInstance().db.showingsByTitle(s, moviesWanted);
                }
                
                allMovies.setModel(App.getAppInstance().db.getJtableSForDisplay(s).getModel());
                
                s  = App.getAppInstance().db.getShows();
        }
    }//GEN-LAST:event_applyFilterActionPerformed

    private void adultNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adultNoActionPerformed

    private void childNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childNoActionPerformed

    private void studentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNoActionPerformed

    private void pensionerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensionerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pensionerNoActionPerformed

    private void frontNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frontNoActionPerformed

    private void backNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backNoActionPerformed

    private void middleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNoActionPerformed

    public int IsEmpty(String str) {
        int val = 0;
        if (str == null ||str.equals("")){
            return val;
        }else{
            val = Integer.parseInt(str);
            if (val < 0){
                val = val*-1;
            }
        }
        return val;
    }
    public String IsEmpty(String str,String replaceWith) {
        
        if (str == null ||str.equals("")){
            return null;
        }
        return str;
    }
    
    public void RefreshFrame(){
        scheduler.shutdown();
        new CustomerBookingGUI(this.customer).setVisible(true);
        this.setVisible(false);
    }
        
    private void bookMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookMovieActionPerformed
//      dfa
        String mName = movieName.getText();

        // Parse date
        String bDate = date.getText();
        Date sDate = null;

        
        LocalDateTime timeOfBooking = LocalDateTime.now();
        String bLocation = location.getText();
        String bTime = time.getText();
        String bCinemaType = (String)cinemaType.getSelectedItem();
        String child = childNo.getText();
        String adult = adultNo.getText();
        String student = studentNo.getText();
        String pensioner = pensionerNo.getText();
        String front = frontNo.getText();
        String middle = middleNo.getText();
        String back = backNo.getText();
        
        if(mName.equals("")|| bDate.equals("")
                || bLocation.equals("")||bTime.equals("")
                ||bCinemaType.equals("")||bDate.equals("")){
            JOptionPane.showMessageDialog(null,"Error Adding Booking: Some Required Input Boxes Are Still Empty","Unsuccessful Booking Attempt", JOptionPane.ERROR_MESSAGE);
            App.getAppInstance().db.updateCancelledBookingsCSV(0, this.customer.name, this.customer.username, LocalDateTime.now(), "Invalid Booking Input");
           
            return;}
        try {
            sDate = new SimpleDateFormat("dd/MM/yyyy").parse(bDate);}
        catch (Exception e) {
                System.out.println("Error: Parsing Given Date");
                JOptionPane.showMessageDialog(null,"Error: Parsing Given Date","Invalid Booking Attempt", JOptionPane.ERROR_MESSAGE);
                App.getAppInstance().db.updateCancelledBookingsCSV(0, this.customer.name, this.customer.username, LocalDateTime.now(), "Invalid Booking Input");
                return;
                }
        
//        CHECK:  No of Seats chosen match number of people
        if ((IsEmpty(front)+ IsEmpty(middle) + IsEmpty(back)) != (IsEmpty(child)+ IsEmpty(adult) + IsEmpty(student)+ IsEmpty(pensioner))){
                System.out.println("Error: No of Seats chosen don't match number of people");
                JOptionPane.showMessageDialog(null,"Error: No of seats chosen don't match number of people","Invalid Booking Attempt", JOptionPane.ERROR_MESSAGE);
                App.getAppInstance().db.updateCancelledBookingsCSV(0, this.customer.name, this.customer.username, LocalDateTime.now(), "Invalid Booking Input");

                return;
        }
        
        //        SETUP SEATS 
        HashMap<String, Integer> seats = new HashMap<String, Integer>();
        seats.put("front",IsEmpty(front));
        seats.put("middle",IsEmpty(middle));
        seats.put("back",IsEmpty(back));
        
        //        SETUP AGES
        HashMap<String, Integer> ages = new HashMap<String, Integer>();
        ages.put("Adult",IsEmpty(adult));
        ages.put("Student",IsEmpty(student));
        ages.put("Pensioner",IsEmpty(pensioner));
        ages.put("Child",IsEmpty(child));
        
//       CHECK IF THE CUSTOMER HAS SAVED DETAILS BEFORE AND INITLAISE THE TEXTBOXES BEFOREHAND
        String cName = cardName.getText();
        
        String cNumber = String.valueOf(creditCardNo.getPassword());
        
        String gNumber = giftCardNo.getText();
        
//       ///////////////// MAIN CODE ///////////////////////////////////////

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime sTime = LocalDateTime.parse(bDate+" "+bTime, formatter);
        System.out.println("Movie Name: " + mName + " Location: " + bLocation + " Session Date: " + sDate + " Room Type: " + bCinemaType + " Show Session: " + bTime);
        String res = App.getAppInstance().db.book(seats, ages, timeOfBooking, this.customer.name, IsEmpty(gNumber,null), IsEmpty(cNumber,null), mName, bLocation, sDate, bCinemaType, sTime);
        
        try {
            int bID = Integer.parseInt(res);
            Booking booking = App.getAppInstance().db.getBooking(bID);
            String receipt = "\n##################################################\n" +
                             "################## NAAAR Movie Booking System \u00a9 ###################\n" +
                             "##################################################\n\n"+
                             "Date: " + booking.getTimeOfBooking() + "\n" + 
                             "Name: " +  this.customer.name + "\n" +
                             "Card Number: " +  "XX"+  this.customer.creditCardNo.substring(this.customer.creditCardNo.length() - 3) + "\n" + // % 100000
                            "Booking Number: " + booking.getBookingID() + "\n" +
                            ages.toString() + "\n"+ 
                            
                            "----------------------------------------------------\n" +
                            "Total Price:                " + booking.getPrice() + "\n" +
                            "No of Seats:                " + booking.getTotalSeats() + "\n" +
                            "\n##################################################\n"; 
            JOptionPane.showMessageDialog(null,receipt,"Successful Booking - Receipt", JOptionPane.INFORMATION_MESSAGE);
            new CustomerMainGUI(this.customer).setVisible(true);
            this.setVisible(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,res,"Booking Attempt", JOptionPane.ERROR_MESSAGE);
            App.getAppInstance().db.updateCancelledBookingsCSV(0, this.customer.name, this.customer.username, LocalDateTime.now(), res);

}
        
//        
        
    }//GEN-LAST:event_bookMovieActionPerformed

    private void allMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allMoviesMouseClicked
        allMovies.setEnabled(false);
    }//GEN-LAST:event_allMoviesMouseClicked

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CustomerBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CustomerBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CustomerBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CustomerBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CustomerBookingGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adultNo;
    private javax.swing.JTable allMovies;
    private javax.swing.JButton applyFilter;
    private javax.swing.JButton back;
    private javax.swing.JTextField backNo;
    private javax.swing.JButton bookMovie;
    private javax.swing.JTextField cardName;
    private javax.swing.JTextField childNo;
    private javax.swing.JComboBox<String> cinemaType;
    private javax.swing.JPasswordField creditCardNo;
    private javax.swing.JTextField date;
    private javax.swing.JTextField frontNo;
    private javax.swing.JTextField giftCardNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField location;
    private javax.swing.JComboBox<String> locationf;
    private javax.swing.JTextField middleNo;
    private javax.swing.JTextField movieName;
    private javax.swing.JTextField movieWantedf;
    private javax.swing.JTextField pensionerNo;
    private javax.swing.JCheckBox saveCard;
    private javax.swing.JComboBox<String> screenTypef;
    private javax.swing.JComboBox<String> showingWeekf;
    private javax.swing.JTextField studentNo;
    private javax.swing.JTextField time;
    private javax.swing.JComboBox<String> timef;
    // End of variables declaration//GEN-END:variables
}
